examsolution/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth.views import LogoutView

app_name = "examsolution"
urlpatterns = [
   
    path('', views.home, name='home'),
    path('site_map', views.site_maps_view),
    path('notes/', views.notes, name='notes'),
    path('topicalpastpaper/', views.index_topical_past_paper, name='topical_past_paper'),
    path('topicalpastpaper/<exam_board>', views.subject_topical_past_paper, name='subject_topical_past_paper'),
    path('topicalpastpaper/<exam_board>/<subject_selected>', views.topics_topical_past_paper, name='topics_topical_past_paper'),
    path('topicalpastpaper/<exam_board>/<subject_selected>/<int:topic_id>', views.view_topical_past_paper, name='view_topical_past_paper'),
    path('pastpapers/', views.index_past_papers, name='past_papers'),
    path('pastpapers/<exam_board>',views.subject_past_papers,name='subject_past_papers'),
    path('pastpapers/<exam_board>/<subject_selected>', views.year_past_papers, name='year_past_papers'),
    path('pastpapers/<exam_board>/<subject_selected>/<year>', views.view_past_paper , name='view_past_paper'),
    path('testyourself/', views.index_test_yourself, name='test_yourself'),
    path('testyourself/<question_id>/', views.taking_test, name='taking_test'),
    path('testyourself/<question_id>/grading/', views.test_grading, name='test_grading'),
    path('worksheets/', views.worksheets, name='worksheets'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about_us/',views.about_us,name='about_us'),
    path('privacy/',views.privacy, name='privacy'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    
    path('login/',CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page='examsolution:home'),name='logout'),
    path('register/',RegisterPage.as_view(),name='register'),
    
    path('my_to_do_list/',UserTaskList.as_view(),name='my_to_do_list'),
    path('my_to_do_list/<int:pk>/', UserTaskDetail.as_view(),name='task'),
    path('my_to_do_list/create_task/', UserTaskCreate.as_view(),name='create_task'),
    path('my_to_do_list/update_task/<int:pk>/',UserTaskUpdate.as_view(),name='update_task'),
    path('my_to_do_list/delete_task/<int:pk>/',DeleteView.as_view(),name='delete_task'),
    
    path('my_progress/', UserProgressList.as_view(),name='my_progress'),
    path('my_progress_record/', UserProgressRecordCreate.as_view(),name='my_progress_record'),
    path('revision/<paper_to_revise>/', views.full_revision_of_written_paper,name='full_revision_of_written_paper'),

    path('blog/',views.blog_post_home, name='blog_post_home'),
    path("<title>/<int:year>/<int:month>/<int:day>/<int:id>/", views.read_articlet, name="read_article")
    
]

piilearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from .sitemaps import FullQuestionAnswersSiteMap

sitemaps = {
    'fullquestionanswers' : FullQuestionAnswersSiteMap,
    
}

urlpatterns = [
    path('', include('examsolution.urls')),
    path('admin/', admin.site.urls),
    # new sitemap url below
    # path('sitemap.xml',sitemap, {"sitemaps":sitemaps})
]

examsolution/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Year(models.Model):
    year = models.IntegerField()
 
    def __str__(self):
        return str(self.year)
    
    class Meta:
        ordering = ['-year']
    
class ExamBoard(models.Model):
    exam_board = models.CharField(max_length=200)
    
    def __str__(self):
        return self.exam_board
    
class Session(models.Model):
    session = models.CharField(max_length=200)
    
    def __str__(self):
        return self.session
    
class Paper(models.Model):
    paper_num = models.IntegerField()
    
    def __str__(self):
        return str(self.paper_num)
    
class Subject(models.Model):
    exam_board_key = models.ForeignKey(ExamBoard, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    
    def __str__(self):
        return self.subject
    
    class Meta:
        ordering = ['subject']
    
class BoardSubTopic(models.Model):
    subject_key = models.ForeignKey(Subject, on_delete=models.CASCADE, null='False')
    paper_num_key = models.ForeignKey(Paper, on_delete=models.CASCADE, null='False')
    topic = models.CharField(max_length=200)
    
    def __str__(self):
        return self.subject_key.subject + " " + self.topic + "(" + str(self.paper_num_key.paper_num) + ")" 
    
    
class QuestionAnswer(models.Model):
    board_sub_topic_key = models.ForeignKey(BoardSubTopic, on_delete=models.CASCADE)
    year_key = models.ForeignKey(Year, on_delete=models.CASCADE)
    session_key = models.ForeignKey(Session, on_delete=models.CASCADE)
    question_name = models.CharField(max_length=200)
    question_google_drive_link = models.URLField(max_length=200)
    # question_directory = models.FileField(null=True,blank=True,upload_to='TopicalQuestions')
    answer_name = models.CharField(max_length=200)
    answer_google_drive_link = models.URLField(max_length=200)
    # answer_directory = models.FileField(null=True,blank=True,upload_to='TopicalAnswers')
    detailed_answer_link = models.CharField(max_length=500, blank=True, null=True)
    video_explanation_link = models.CharField(max_length=500, blank=True, null=True)
    exam_report_comment = models.CharField(max_length=20000, blank=True)
    

    
    def __str__(self):
        return self.board_sub_topic_key.subject_key.exam_board_key.exam_board + " " + self.board_sub_topic_key.subject_key.subject + " " + str(self.year_key.year) + " " + self.session_key.session + " " + str(self.board_sub_topic_key.paper_num_key.paper_num) + " " + self.board_sub_topic_key.topic + " (" + self.question_name + ") " + " (" + self.answer_name + ") "
    

class FullQuestionAnswer(models.Model):
    subject_key = models.ForeignKey(Subject, on_delete=models.CASCADE, null='False')
    year_key = models.ForeignKey(Year, on_delete=models.CASCADE)
    session_key = models.ForeignKey(Session, on_delete=models.CASCADE)
    full_question_name = models.CharField(max_length=200)
    google_drive_question_link = models.URLField(max_length=200,null=True, blank=True)
    full_question_directory = models.FileField(null=True,upload_to='FullQuestionPaper')
    full_answersheet_name = models.CharField(max_length=200)
    google_drive_answer_link = models.URLField(max_length=200,null=True, blank=True)
    full_answersheet_directory = models.FileField(null=True,upload_to='FullMarkScheme')
    paper_number = models.ForeignKey(Paper,on_delete=models.CASCADE,blank=True,null=True)
    A_raw_mark_req = models.IntegerField(blank=True, null=True)
    B_raw_mar_req = models.IntegerField(blank=True, null=True)
    C_raw_mar_req = models.IntegerField(blank=True, null=True)
    D_raw_mar_req = models.IntegerField(blank=True, null=True)
    E_raw_mar_req = models.IntegerField(blank=True, null=True)
    general_exam_report_cmnt = models.CharField(max_length=20000,blank=True, null=True)
    

    
    
    def __str__(self):
        return str(self.year_key.year) + " ("+ self.session_key.session + ") "+ " " + self.subject_key.subject + " " + " (" + self.full_question_name + ") " + " (" + self.full_answersheet_name + ") "

    
class ReportThreshPrep(models.Model):
    subject_key = models.ForeignKey(Subject,on_delete=models.CASCADE)
    year_key = models.ForeignKey(Year, on_delete=models.CASCADE)
    session_key = models.ForeignKey(Session, on_delete=models.CASCADE)
    extra_name = models.CharField(max_length=500)
    extra_directory = models.FileField(null=True,upload_to='ReportThreshPrep')
    
    def __str__(self):
        return self.extra_name + " " + str(self.year_key.year) + " ("+ self.session_key.session + ") "+ " " + self.subject_key.subject + " "
    
class PossibleLetters(models.Model):
    letter = models.CharField(max_length=1)
    
    def __str__(self):
        return self.letter
    
class PossibleQuestionNumber(models.Model):
    question_number = models.IntegerField()
    
    def __str__(self):
        return str(self.question_number)
    
class PaperOneAnswers(models.Model):
    paper_one_name_key = models.ForeignKey(FullQuestionAnswer,on_delete=models.CASCADE)
    question_number_key = models.ForeignKey(PossibleQuestionNumber,on_delete=models.CASCADE)
    question_answer_key = models.ForeignKey(PossibleLetters,on_delete=models.CASCADE)
    question_category = models.CharField(max_length=500,null=True,blank=True)
    question_examreportcmt = models.CharField(max_length=20000,null=True,blank=True)
    question_video_explanation = models.URLField(max_length=1000,null=True,blank=True)
    
    def __str__(self):
        return str(self.question_number_key.question_number) + " ("+ self.question_answer_key.letter +") " +" ("+ self.paper_one_name_key.full_question_name + ") "
    
class website_pics(models.Model):
    website_logo = models.ImageField(null=True,upload_to='WesbitePics')

class home_image(models.Model):
    home_logo = models.ImageField(null=True,upload_to='WesbitePics')


class people_image(models.Model):
    name_of_pic = models.CharField(max_length=2000)
    picture = models.ImageField(null=True,upload_to='WesbitePics')
    
    def __str__(self):
        return self.name_of_pic
    
# user related tables

class UserTask(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']
    
class UserProgressRecord(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    subject_of_paper_written = models.CharField(max_length=200,null=True,blank=True)
    paper_written = models.CharField(max_length=200)
    raw_mark = models.IntegerField(null=True, blank=True)
    percentage = models.CharField(max_length=50,null=True, blank=True)
    letter_grade = models.CharField(max_length=1,null=True, blank=True)
    hours_taken = models.IntegerField(null=True, blank=True)
    minutes_taken = models.IntegerField(null=True, blank=True)
    questions_failed = models.CharField(max_length=2000,null=True, blank=True)
    date_completed = models.DateTimeField(auto_now_add=True)
    subject_of_paper_written = models.CharField(max_length=200,null=True,blank=True)
    user_answer_input = models.CharField(max_length=2000,null=True,blank=True)
    
    def __str__(self):
        return self.paper_written
    
    class Meta:
        ordering = ['-date_completed']

class ContactUsInfo(models.Model):
    sender_name = models.CharField(max_length=200)
    sender_email = models.EmailField()
    sender_message = models.TextField()
    
    def __str__(self):
        return self.sender_name
    
## Blog Models

class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    #title of the blog post (varchar with max length 250 characters).
    content = models.TextField()
    #content of the blogpost in text format, can be long and contain images
    #or other media files as well.(text field to store large amount of data.)
    date_posted = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

examsolution/forms.py
# from django import forms
# from django.forms import ModelForm
# from .models import *
# from .views import *


# question_answer = QuestionAnswer.objects.all()

# questions_available = []
# for x in question_answer:
#     questions_available.append(x.question_name)

# QUESTION_AVAILABLE_CHOICES = []

# QUESTION_AVAILABLE_CHOICES.insert(0,('None',''))

# number_of_questions_available = len(questions_available)
# for x in range(number_of_questions_available):
#     array_index_needed = x + 1
#     QUESTION_AVAILABLE_CHOICES.insert(array_index_needed,(questions_available[x],questions_available[x]))



# class QuestionSearchForm(forms.Form):
#     question_search = forms.ChoiceField(choices=QUESTION_AVAILABLE_CHOICES, widget=forms.Select(attrs={'onchange': 'submit();'}))
    
    
# # Exam Board Search starts here

# # Below

# exam_board_choices = ExamBoard.objects.all()
# exam_board_available = []
# for exam_baord in exam_board_choices:
#     exam_board_available.append(exam_baord.exam_board)

# EXAM_BOARD_CHOICES = []
# EXAM_BOARD_CHOICES.insert(0,('None',''))
# exam_baord_num = len(exam_board_available)

# for x in range(exam_baord_num):
#     index_needed = x + 1
#     EXAM_BOARD_CHOICES.insert(index_needed,(exam_board_available[x],exam_board_available[x]))
    
# # Exam Board Search ends here
# # Subject Search starts here
    
# subject_choices = Subject.objects.all()
# subject_available = []
# for subject in subject_choices:
#     subject_available.append(subject.subject)
    
# SUBJECT_CHOICES = []
# SUBJECT_CHOICES.insert(0,('None',''))
# subject_num = len(subject_available)


# for x in range(subject_num):
#     index_needed = x + 1
#     SUBJECT_CHOICES.insert(index_needed,(subject_available[x],subject_available[x]))

# # Subject Search starts here
# # Paper Search starts here

# paper_choices = Paper.objects.all()
# paper_available = []
# for paper in paper_choices:
#     paper_available.append(paper.paper_num)
    
# PAPER_NUMBER_CHOICES  = []
# PAPER_NUMBER_CHOICES.insert(0,('None',''))
# paper_number = len(paper_available)

# for x in range(paper_number):
#     index_needed = x + 1
#     PAPER_NUMBER_CHOICES.insert(index_needed,(str(paper_available[x]),str(paper_available[x])))

# # Paper Search ends here
# # Topic Search starts here
# topic_choices = BoardSubTopic.objects.all()
# topics_available = []
# for topic in topic_choices:
#     topics_available.append(topic.topic)
    
# TOPIC_CHOICES = []
# TOPIC_CHOICES.insert(0,('None',''))
# topics_len = len(topics_available)

# for x in range(topics_len):
#     index_needed = x + 1
#     TOPIC_CHOICES.insert(index_needed,(topics_available[x],topics_available[x]))

# # Topic Search end here
# # Year Search starts here
# year_choices = Year.objects.all()
# years_available = []
# for year in year_choices:
#     years_available.append(year.year)
    
# YEAR_CHOICES = []
# YEAR_CHOICES.insert(0,('None',''))
# years_len = len(years_available)

# for x in range(years_len):
#     index_needed = x + 1
#     YEAR_CHOICES.insert(index_needed,(str(years_available[x]),str(years_available[x])))
# # Year Search ends here
# # Session Search starts here
# session_choices = Session.objects.all()
# session_available = []
# for session in session_choices:
#     session_available.append(session.session)
    
# SESSION_CHOICES = []
# SESSION_CHOICES.insert(0,('None',''))
# session_len = len(session_available)

# for x in range(session_len):
#     index_needed = x + 1
#     SESSION_CHOICES.insert(index_needed,(str(session_available[x]),str(session_available[x])))
# # Session Search ends here


# class SearchForm(forms.Form):
#     subject_search = forms.ChoiceField(choices=SUBJECT_CHOICES, label='Subject',required=False, widget=forms.Select(attrs={'onchange': 'submit();'}))
#     paper_search = forms.ChoiceField(choices=PAPER_NUMBER_CHOICES, label='Paper', required=False, widget=forms.Select(attrs={'onchange':'submit()'}))
#     topic_search = forms.ChoiceField(choices=TOPIC_CHOICES, label='Topic', required=False , widget=forms.Select(attrs={'onchange':'submit()'}))
#     year_search = forms.ChoiceField(choices=YEAR_CHOICES, label='Year', required=False, widget=forms.Select(attrs={'onchange':'submit()'}))
#     session_search = forms.ChoiceField(choices=SESSION_CHOICES, label='Session', required=False, widget=forms.Select(attrs={'onchange':'submit()'}))


# class ExamBoardSearchForm(forms.Form):
#     exam_board_search = forms.ChoiceField(choices=EXAM_BOARD_CHOICES, label='Exam Board', required=True)



##### Views part
    # question_search_form = SearchForm(request.POST or None)
    # subject_searched = ''
    # paper_searched = ''
    # topic_searched = ''
    # year_searched = ''
    # session_searched = ''

    
    # if question_search_form.is_valid():
    #     subject_searched = question_search_form.cleaned_data.get('subject_search')
    #     paper_searched = question_search_form.cleaned_data.get('paper_search')
    #     topic_searched = question_search_form.cleaned_data.get('topic_search')
    #     year_searched = question_search_form.cleaned_data.get('year_search')
    #     session_searched = question_search_form.cleaned_data.get('session_search')
        

examsolution/templates/examsolution/college.html
{% extends 'examsolution/base.html' %}
{% load static %}
{% block title %}Collge{% endblock title %}


{% block content %}

<a href=" {% url 'examsolution:home' %} ">Back To Home Page</a>

<h1> {{exam_board_searched}} </h1>

{% endblock content %}

examsolution/templates/examsolution/subject_topical_past_paper.html
{% extends 'examsolution/base.html' %}
{% load static %}

{% block title %}Topical Past Papers | {{exam_board_selected.exam_board}} | Pii Learn{% endblock title %}



{% block content %}


<section class="subjects">

    {% if exam_board_selected.subject_set.all %}
        <div class="panel_heading">
            <p>You're looking at {{exam_board_selected.exam_board}} subjects</p>
            <a href="{% url 'examsolution:topical_past_paper' %}">Reselect exam board</a>
        </div>

        {% comment %} {% for subject in exam_board_selected.subject_set.all  %}
                <a class="subject" href="{% url 'examsolution:topics_topical_past_paper' exam_board_selected.exam_board subject.subject %}">{{subject.subject}}</a>
        {% endfor %} {% endcomment %}

        <a class="subject" href="{% url 'examsolution:topics_topical_past_paper' exam_board_selected.exam_board 'Mathematics ~ 9709' %}">Mathematics ~ 9709</a>
        <a class="subject" href="{% url 'examsolution:topics_topical_past_paper' exam_board_selected.exam_board 'Further Mathematics ~ 9231' %}">Further Mathematics ~ 9231</a>
        

    {% else %}
        <div class="panel_heading">
            <p>{{exam_board_selected.exam_board}} questions <strong>Coming soon!</strong></p>
            <a href="{% url 'examsolution:topical_past_paper' %}">Reselect exam board</a>
        </div>
    {% endif %}

</section>

{% endblock content %}

examsolution/templates/examsolution/test_grading.html
{% extends 'examsolution/base.html' %}
{% load static %}
{% block title %}Test Grading | Pii Learn{% endblock title %}

{% block content %}

<section class="general_comments">
    <p class="grading_page_heading">
        Below are the general exam report comment for <strong> {{mcq_paper_selected.full_question_name}}</strong>
    </p>
 
    {% if mcq_paper_selected.general_exam_report_cmnt %}

        <p class="general_cmt_para"> {{mcq_paper_selected.general_exam_report_cmnt}} </p>
    
    {% else %}

        <p class="general_cmt_para">general comments for this paper not available</p>

    {% endif %}

</section>



<div class="test_grading_piilearn_record" style="
background-color: white;
margin-left: 2.5rem;
margin-right: 2.5rem;
margin-top: 2rem;
padding: 1rem;
font-size: 2rem;
border-radius: 2.5rem;

">
    <p>
        Well done for completing <strong> {{mcq_paper_selected.full_question_name}}</strong>.
        If you want to keep data for this paper. Allow Pii Learn to record your data below.
    </p>

    <form method='POST' action="{% url 'examsolution:my_progress_record'%}">
        {% csrf_token %}

        <input type='text' value='{{mcq_paper_selected.subject_key.subject}}' name='subject_of_paper_written' style="display: none;">
        <input type='text' value='{{mcq_paper_selected.full_question_name}}' name='paper_written' style="display: none;">
        <input type='text' value='{{score}}' name='raw_mark' style="display: none;">
        <input type='text' value='{{percentage}}' name='percentage' style="display: none;">
        <input type='text' value='{{grade}}' name='letter_grade' style="display: none;">
        <input type='text' value='{% for wrong_question in wrong_question %}{{wrong_question}},{% endfor %}' name='questions_failed' style="display: none;">
        <input type='text' value='{% for each_answer in user_answer_input %}{{each_answer}}{% endfor %}' name='user_answer_input' style="display: none;">
        
        <input type='submit' value='Record my data' style="border-radius:2.5rem;padding:1rem;margin-top:0.5rem;background-color:black;color:white;font-size:2rem;">
    </form>
</div>


<section class="view_test_data" id="view_test_data_grading">
    <p class="grading_page_heading">
        Use the statics below to evaluate yourself
    </p>
    <div class="statistics">


        <div class="grading_data">
            <h1>You got {{score}} </h1>
            <p>
                {% if score == 40 %}
                    You got everything correct!

                {% else %}

                    These are the questions you got wrong <br>
                    {% for wrong_question in wrong_question %}
                        <strong>{{wrong_question}},</strong>
                    
                    {% endfor %}

                
                {% endif %}
                
            </p>
        </div>


        <div class="grading_data">
            <h1>Your percentage is  {{percentage}}%</h1>
        </div>

        <div class="grading_data">
            {% if grade %}
                <h1>Your grade is {{grade}} </h1>

            {% else %}
                <h1>Threshold Data for <strong> {{mcq_paper_selected.full_question_name}}</strong>  paper not available</h1>
            {% endif %}
            <p>Your grade is calucate based on the threshold of <strong> {{mcq_paper_selected.full_question_name}}</strong> paper. These are some of the values below <br>
                A ~ {{mcq_paper_selected.A_raw_mark_req}} {% if mcq_paper_selected.A_raw_mark_req %} and above {% endif %} 
                <br>
                B ~ {{mcq_paper_selected.B_raw_mar_req}} {% if mcq_paper_selected.B_raw_mar_req %} and above {% endif %} 
                <br>
                C ~ {{mcq_paper_selected.C_raw_mar_req}} {% if mcq_paper_selected.C_raw_mar_req %} and above {% endif %} 
                <br>
                D ~ {{mcq_paper_selected.D_raw_mar_req}} {% if mcq_paper_selected.D_raw_mar_req %} and above {% endif %} 
                <br>
                E ~ {{mcq_paper_selected.E_raw_mar_req}} {% if mcq_paper_selected.E_raw_mar_req %} and above {% endif %} 
                <br>
            </p>
           
        </div>


    </div>

    
</section>

<section class="further_question_explanation">
    <p class="grading_page_heading">
       <strong> {{mcq_paper_selected.full_question_name}}</strong> questions with exam report comments
    </p>

    {% for mcq_question in mcq_paper_selected_set %}

        {% if mcq_question.question_examreportcmt %}

            <p class="grading_er_comment_heading"> Question {{mcq_question.question_number_key}}</p>
            <p class="grading_er_comment">{{mcq_question.question_examreportcmt}}</p>

        {% endif %}

    {% endfor %}
    
</section>


{% endblock content %}

examsolution/templates/examsolution/topical_past_paper.html
{% extends 'examsolution/base.html' %}
{% load static %}

{% block title %}Topical Past Papers | Pii Learn{% endblock title %}


{% block content %}


<section class="exam_boards">
    {% if exam_board_list %}

            {% for exam_board in exam_board_list %}
            
                    <a class="exam_board" href="{% url 'examsolution:subject_topical_past_paper' exam_board.exam_board %}">{{exam_board.exam_board}} </a>

            {% endfor %}

    {% endif %}
</section>


<script src=" {% static 'examsolution/js/script.js' %} "></script>

{% endblock content %}

examsolution/templates/examsolution/topics_topical_past_paper.html
{% extends 'examsolution/base.html' %}
{% load static %}

{% block title %} Topical Past Papers | {{exam_board}} | {{subject_selected}} | Pii Learn{% endblock title %}


{% block content %}

<section class="topics">


{% if topic_paper_list %}
    <div class="panel_heading">
        <p>You're seeing {{subject_selected}} topics</p>
        <a href="{% url 'examsolution:subject_topical_past_paper' exam_board %}">Reselect subject</a>
    </div>


    {% for topic in topic_paper_list %}
        <a class="topic" href="{% url 'examsolution:view_topical_past_paper' exam_board subject_selected topic.id %}">{{topic.topic}} ~ Paper {{topic.paper_num_key}}</a>
    {% endfor %}

{% else %}
    <div class="panel_heading">
        <p>{{subject_selected}} topical questions <strong>Coming Soon!</strong></p>
        <a href="{% url 'examsolution:subject_topical_past_paper' exam_board %}">Reselect subject</a>
    </div>
{% endif %}
</section>

{% endblock content %}

examsolution/templates/examsolution/usertask_confirm_delete.html
{% extends 'examsolution/base.html' %}
{% load static %}
{% block title %}Delete | {{task.title}} | Pii Learn{% endblock title %}


{% block content %}

<div class="piilearn_wrap_container">

    <div class="header_bar">
        <a href="{% url 'examsolution:my_to_do_list' %}">&#8592;Back</a>
    </div>

    <div class="card-body">
        <form method="POST" action="">
            {% csrf_token %}
            <p>Are you sure you wanna delete task with title <i>{{task.title}}</i>? </p>
            <input type="submit" value="Delete" class="all_buttons">
        </form>
    </div>

</div>

{% endblock content %}

examsolution/templates/examsolution/usertask_form.html
{% extends 'examsolution/base.html' %}
{% load static %}
{% block title %}Add a new task | Pii Learn{% endblock title %}


{% block content %}

<div class="piilearn_wrap_container">
    <div class="header_bar">
        <a href="{% url 'examsolution:my_to_do_list' %}">&#8592;Back</a>
    </div>

    <div class="card-body">

        <h3>Add your new task below</h3>

        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create" class="all_buttons">
    
        </form>
    
    </div>
</div>



{% endblock content %}

examsolution/templates/examsolution/usertask_list.html
{% extends 'examsolution/base.html' %}
{% load static %}
{% block title %}My ToDo List | Pii Learn{% endblock title %}


{% block content %}

<div class="piilearn_wrap_container">

    <div class="header_bar">
        <div>
            <h1> Hello {{request.user|title}} </h1>
            <h3> You have {{count}} incomplete task{{count|pluralize:"s"}}</h3>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'examsolution:logout' %}">Logout</a>

        {% else %}
            <a href="{% url 'examsolution:login' %}">Login</a>
        {% endif %}

    </div>

    <div id="search-add-wrapper">
        <form method="GET" style="margin-top:20px; display:grid;" id="usertask_list_search_form">
            <input type='text' name="search_area" value={{search_input}}>
            <input type='Submit' value="Search" class="all_buttons">
        </form>
        <a id="add-link" href="{% url 'examsolution:create_task' %}">&#x2b;</a>
    </div>

    <div class="task-items-wrapper">

        {% for task in usertasklist %}
            <div class="task-wrapper">
                {% if task.complete %}
                    <div class="task-title">
                        <div class="task-complete-icon"></div>
                        <i><a style="text-decoration: line-through; font-weight:none !important;" href="{% url 'examsolution:update_task' task.id %}"> {{task.title}} </a></i>
                    </div>
                    <a class="delete-link" href="{% url 'examsolution:delete_task' task.id %}">&#215;</a>
                {% else %}

                    <div class="task-title">
                        <div class="task-incomplete-icon"></div>
                        <a href="{% url 'examsolution:update_task' task.id %}"> {{task.title}} </a>
                    </div>
                    <a class="delete-link" href="{% url 'examsolution:delete_task' task.id %}">&#215;</a>
                    
                {% endif %}
                
            </div>

        {% empty %}
            <h3> {{request.user.username|title}}, you have no tasks on your schedule.</h3>
        {% endfor %}
    
    </div>

</div>

{% endblock content %}

examsolution/templates/examsolution/worksheet.html
{% extends 'examsolution/base.html' %}
{% load static %}
{% block title %}Collge | Pii Learn{% endblock title %}


{% block content %}

<a href=" {% url 'examsolution:home' %} ">Back To Home Page</a>

<h1> {{exam_board_searched}} </h1>

{% endblock content %}